# Generated by Django 5.1.4 on 2025-01-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100, null=True)),
                ('role', models.CharField(max_length=100)),
                ('loginDate', models.DateTimeField(auto_now_add=True)),
                ('onlineTime', models.IntegerField(default=0)),
                ('button1Counter', models.IntegerField(default=0)),
                ('button2Counter', models.IntegerField(default=0)),
            ],
        ),
    ]
